repos:
  - repo: https://github.com/hakancelikdev/unimport
    rev: stable
    hooks:
      - id: unimport
        args:
          - --include-star-import
          - --ignore-init
          - --gitignore
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.7
    hooks:
      # Run the linter.
      - id: ruff
        args: [--line-length=120]
      # Run the formatter.
      - id: ruff-format
